### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by Ladsgroup** [wmde/grafana-dashboards#2]
I want to use it, It would be nice if you add a license like MIT or GPL.

**Comment by addshore** [comment]
Well, we could set the licence to CC0...
Not really sure where you would reuse the dashboards here, as they are very specific to the data collected by us.
Unless you mean the fetch script?

**Comment by Ladsgroup** [comment]
I want to use the fetch script :)

**Comment by addshore** [comment]
Done in 323980d081f0d7e3d6eaa2825461dc06a48e330f

**Comment by Ladsgroup** [comment]
Thanks. I used it in https://github.com/wiki-ai/grafana-dashboards
